name: Generate Pixel Runner

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pixel Runner animation
        uses: Platane/runner@v1
        with:
          github_user_name: egi616       
          outputs: dist/runner.svg
          color_bg: "000000"             
          color_runner: "ff0066"        
          color_path: "00ffff"           
          speed: 1.2                     

      - name: Push the runner.svg file
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
